export const templateList = [
  {
    id: "1",
    name: "Template 1",
    thumbnailUrl: "assets/images/thumbnailCata.jpg",
    rating: "",
  },
  {
    id: "2",
    name: "Template 1",
    thumbnailUrl: "assets/images/thumbnailCata.jpg",
    rating: "5",
  },
  {
    id: "3",
    name: "Template 1",
    thumbnailUrl: "assets/images/thumbnailCata.jpg",
    rating: "3",
  },
  {
    id: "2",
    name: "Template 2",
    thumbnailUrl: "assets/images/thumbnailCata.jpg",
    rating: "3",
  },
  {
    id: "3",
    name: "Template 3",
    thumbnailUrl: "assets/images/thumbnailCata.jpg",
    rating: "4",
  },
  {
    id: "4",
    name: "Template 4",
    thumbnailUrl: "assets/images/thumbnailCata.jpg",
    rating: "3",
  },
  {
    id: "5",
    name: "Template 5",
    thumbnailUrl: "assets/images/thumbnailCata.jpg",
    rating: "1",
  },
  {
    id: "1",
    name: "Template 1",
    thumbnailUrl: "assets/images/thumbnailCata.jpg",
    rating: "",
  },
  {
    id: "1",
    name: "Template 1",
    thumbnailUrl: "assets/images/thumbnailCata.jpg",
    rating: "5",
  },
  {
    id: "1",
    name: "Template 1",
    thumbnailUrl: "assets/images/thumbnailCata.jpg",
    rating: "3",
  },
  {
    id: "2",
    name: "Template 2",
    thumbnailUrl: "assets/images/thumbnailCata.jpg",
    rating: "3",
  },
  {
    id: "3",
    name: "Template 3",
    thumbnailUrl: "assets/images/thumbnailCata.jpg",
    rating: "4",
  },
  {
    id: "4",
    name: "Template 4",
    thumbnailUrl: "assets/images/thumbnailCata.jpg",
    rating: "3",
  },
  {
    id: "5",
    name: "Template 5",
    thumbnailUrl: "assets/images/thumbnailCata.jpg",
    rating: "1",
  },
];
